### ISSUE TITLE
Player stats in game not work

### ISSUE THREAD

**Issue by S11720037** [MythB/BombSquad-Mods#1]
You mod is great

![Screenshot at 2019-09-15 16-04-25](https://user-images.githubusercontent.com/50015208/64918556-9dad6000-d7d2-11e9-9b8b-b91fc398d9f9.png)

I was copied the file to my bombsquad folder mods, but the map not showing when i create custom playlist

![Screenshot at 2019-09-15 16-05-52](https://user-images.githubusercontent.com/50015208/64918567-b6b61100-d7d2-11e9-97d1-c4ff63b48598.png)

![Screenshot_2019_09_15_16_08_42](https://user-images.githubusercontent.com/50015208/64918611-2f1cd200-d7d3-11e9-8c2b-f29795879377.jpg)

**Comment by MythB** [comment]
This mod not working on android. You must create playlist on windows/ubuntu then import

**Comment by S11720037** [comment]
![Screenshot at 2019-09-15 16-41-15](https://user-images.githubusercontent.com/50015208/64918958-aa808280-d7d7-11e9-9792-77720ab1754f.png)

The game is showing, but i cant select the game

**Comment by MythB** [comment]
What error you get on console?

**Comment by S11720037** [comment]
![Screenshot at 2019-09-15 17-20-58](https://user-images.githubusercontent.com/50015208/64919435-377a0a80-d7dd-11e9-8d9a-a29929461771.png)

**Comment by S11720037** [comment]
thanks, its work now

I hope this great mod always update.

**Comment by MythB** [comment]
Btw you must update version to 1.4.150 for admin commands.

**Comment by S11720037** [comment]
> Btw you must update version to 1.4.150 for admin commands.
Yeah, im using 1.4.150.

The new command its very good.

**Comment by LeandergamesYT** [comment]
@S11720037 how you fixed this problem?

**Comment by FireHead90544** [comment]
Same problem here

**Comment by FireHead90544** [comment]
Can u please give that playlist code
