### ISSUE TITLE
How to change the map name

### ISSUE THREAD

**Issue by S11720037** [MythB/BombSquad-Mods#2]
![Screenshot at 2019-11-26 11-24-08](https://user-images.githubusercontent.com/50015208/69597001-70392a00-103f-11ea-9d17-b05c057b1f8f.png)
If i change "Player Stats By MythB" to other, the server will error.

**Comment by MythB** [comment]
Error should be come from playlist. Recreate playlist after changed the name.

**Comment by LeandergamesYT** [comment]
Maybe you have to change the "Player stats BY MythB" by to different positions in your file. Please go in your file, Press CTRL+F and write  `Player Stats By MythB`. There you find the second defining. Change it to yours name and reshare the playlist
