### ISSUE TITLE
admin is not working

### ISSUE THREAD

**Issue by S11720037** [MythB/BombSquad-Mods#3]
hi. i was tried this script in my server but the admin features is doesnt work

i was place my id in admin list but not working
![Screenshot at 2019-07-14 15-47-23](https://user-images.githubusercontent.com/50015208/61180790-b2446f00-a64e-11e9-8bea-69f4acfef9d3.png)

**Comment by MythB** [comment]
Do you have any error in bombsquad console?

**Comment by BHATTYUVRAJ** [comment]
bro plz help admin is not working

**Comment by MythB** [comment]
Use get.account.ID for your ID

**Comment by BHATTYUVRAJ** [comment]
not working ! help make a tutorial on youtube

**Comment by S11720037** [comment]
> Do you have any error in bombsquad console?

![Screenshot at 2019-07-15 19-20-03](https://user-images.githubusercontent.com/50015208/61212687-9667c880-a735-11e9-91f7-91ec23c58b91.png)

**Comment by S11720037** [comment]
> Use get.account.ID for your ID

great.

the admin features is working now.

thanks.

**Comment by S11720037** [comment]
> not working ! help make a tutorial on youtube
use like this bro
![Screenshot at 2019-07-15 19-25-09](https://user-images.githubusercontent.com/50015208/61212970-505f3480-a736-11e9-8b65-b7f6c1d8f594.png)

**Comment by MythB** [comment]
This is my id. Use your account id

**Comment by BHATTYUVRAJ** [comment]
how it works?

**Comment by BHATTYUVRAJ** [comment]
plz tell me
