### ISSUE TITLE
Ranking System

### ISSUE THREAD

**Issue by FireHead90544** [MythB/BombSquad-Mods#3]
Bro your ranking system is not working....nameless game is not adding in playlist....we can only tap on nameless mod but there is no option for select...how to fix it....plzzz...

**Comment by MythB** [comment]
Not working on android otherwise dont forget to change the statsfile location

**Comment by FireHead90544** [comment]
I had changed statsfioe location for my ubuntu server /var/www/html...but when I added mythbadminlist.oy and mythbserverinfo.py to Android mods folder then it shows a nameless game in playlist but there is no option to select that...plzz help me...

**Comment by MythB** [comment]
You must use Windows/Mac OS for adding rank system to playlist.

**Comment by FireHead90544** [comment]
What about a windows server??

**Comment by MythB** [comment]
Create playlist then share/import your playlist from server client
