### ISSUE TITLE
MythBServerInfoLOCAL not make any effect on server

### ISSUE THREAD

**Issue by S11720037** [MythB/BombSquad-Mods#4]
![Screenshot at 2019-07-17 11-10-51](https://user-images.githubusercontent.com/50015208/61344448-e3f24b80-a883-11e9-8b87-d82fe19581ac.png)
all script running without error, but i think MythBServerInfoLOCAL.py not make any effect

**Comment by S11720037** [comment]
![Screenshot at 2019-07-17 11-10-58](https://user-images.githubusercontent.com/50015208/61344523-1e5be880-a884-11e9-93ab-9d7b54fc9ad6.png)
how to make like this?

**Comment by MythB** [comment]
Use this script as game mod(add to playlist)

**Comment by S11720037** [comment]
great.

thankyou
