### ISSUE TITLE
Please Post a Statsfile

### ISSUE THREAD

**Issue by LeandergamesYT** [MythB/BombSquad-Mods#7]
Hi Community,
can someone post a statsfile.json file?
If i start the Server and the Statsgame is coming, "statsfile not exists" gets printed in the Console. Can you send me a template of the file?

Thx

@MythB

**Comment by MythB** [comment]
Just delete stats.json

**Comment by LeandergamesYT** [comment]
bro it isnt working
Can you please tell me step for step how to install the stats system?
Or can you create an Template? What is if there are users that cant read/write python, but would to use your system? It isnt good for users wich no programming experience.
Please write an good manual.
